### ISSUE TITLE
setBorderColor causing error in IE11

### ISSUE THREAD

**Issue by FrankW76** [pepstock-org/Charba#34] opened 2019-04-04 10:01 UTC
> dataset.setBorderColor(borderColors.toArray(new String[0]));

Works fine on all browsers except IE11 gives an error : 

> Unknown.Crx_g$(ArrayString.java:63)
> Unknown.bKx_g$(HovingDataset.java:340)
 

When removing the setBorderColor line the graph work without any problem

**Comment by stockiNail** [comment] 2019-04-04 10:31
@FrankW76 I've tested right now on IE11.

Here my code:

```java
PieDataset dataset = chart.newDataset();
dataset.setBorderWidth(5,5,5,5,5,5,5);
List<String> list = Arrays.asList(Colors.ALL[8].toRGBA(), Colors.ALL[5].toRGBA(),Colors.ALL[13].toRGBA(),Colors.ALL[15].toRGBA(),Colors.ALL[1].toRGBA(),Colors.ALL[0].toRGBA(),Colors.ALL[19].toRGBA());
dataset.setBorderColor(list.toArray(new String[0]));
```

Here the result:

![IE11Border](https://user-images.githubusercontent.com/11741250/55549064-4fe5e500-56d5-11e9-96b2-020b9787b572.png)

I have checked also the code of the error you got it and sounds really strange because is the native object.

May I ask you which chart type you are using (I assumed Pie or Doughnut)?

**Comment by FrankW76** [comment] 2019-04-04 11:07
Noted that also setBorderWidth does not work for me.

>       ResourcesType.setClientBundle(EmbeddedResources.INSTANCE);
> 
>       DoughnutChart chart = new DoughnutChart();
>       chart.getCanvas().getElement().getStyle().setOutlineStyle(Style.OutlineStyle.NONE);
> 
>       DoughnutDataset dataset = new DoughnutDataset();
>       dataset.setBorderWidth(5,5,5,5,5,5,5);

This gives an error

(TypeError) : Kan de eigenschap apply van een niet-gedefinieerde verwijzing of een verwijzing naar een lege waarde niet ophalen

> Unknown.zox_g$(ArrayInteger.java:61)
> Unknown.fKx_g$(HovingDataset.java:412)
> Unknown.kZi_g$(BalanceTileBox.java:152)

With BalanceTileBox.java:152 being the setBorderWidth line.

**Comment by stockiNail** [comment] 2019-04-04 11:19
I've added also the style of canvas you are using and it works fine.

I know it sounds a strange request but could you recompile your GWT application?

**Comment by stockiNail** [comment] 2019-04-11 06:50
I found that Array javascript object has got a method [`Array.from`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) and in Charba implementatio we created a overlay method on Array object with the same name but different signature and not native.

I have the feeling that could create some conflicts (between polyfill and how JSINTEROP acts overlaying methods, I'm still investigating) therefore we have changed the name of Charba method and [committed](https://github.com/pepstock-org/Charba/commit/6e570d14fb3931fd459d2380c5f457ffaf9223e8#diff-9beb370b759b1072ac67c0e1325238ea).

Unfortunately I'm not able to reproduce the issue because, as wrote above, I don't get that error.

**Closed** 2019-05-20 10:07 UTC
