### ISSUE TITLE
Graph on a mobile

### ISSUE THREAD

**Issue by nseb** [pepstock-org/Charba#6] opened 2018-06-18 08:18 UTC
On a mobile version (X Phone) , I have a problem with a  graph , it's not use full space 409pxx350px
![localhost_8080_kartdriver_kartdriver html pixel 2 xl](https://user-images.githubusercontent.com/6363226/41525277-b8a36376-72e0-11e8-9c9c-e3730a23ce56.png)

**Comment by stockiNail** [comment] 2018-06-18 10:04
@nseb Have you set width and height to the chart? You can set also vh and vw items.

**Comment by nseb** [comment] 2018-06-18 10:39
I fix no size I useGWT Material , here the code html generated : 

`<div class="white center-align s12 m8 col" style="padding: 0px; height: 350px; position: absolute; left: 0%; top: 1850px;"><div id="gwt-uid-16" style="position: relative; width: 90%; height: 100%;"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div><canvas class="chartjs-render-monitor" style="display: block; height: 350px; width: 336px;" width="1008" height="1050"></canvas></div><span class="blue darken-4 white-text material-label" style="padding: 12px; position: absolute; bottom: 0px; width: 100%; font-size: 1.2em;">Penalities</span></div>`

**Comment by stockiNail** [comment] 2018-06-18 10:59
May you share GWT Material code? I'm using GWT Material as well but I don't have this behavior.

**Comment by nseb** [comment] 2018-06-18 11:21
Very Simple , it's works a desktop screen , but If change for Mobile Resolution , the problems happened
```
 <ma:masonry.MaterialMasonry margin="1" backgroundColor="GREY_LIGHTEN_3" ui:field="masonry">
 <m:MaterialColumn grid="s12 m8" height="350px" padding="0" textAlign="CENTER"
                                      backgroundColor="WHITE">
                        <c:LineChart ui:field="penalityByRunLineChart"/>
                        <m:MaterialLabel text="Penalities" bottom="0" backgroundColor="BLUE_DARKEN_4"
                                         layoutPosition="ABSOLUTE" padding="12" fontSize="1.2em" textColor="WHITE"
                                         width="100%"/>
                    </m:MaterialColumn>
</ma:masonry.MaterialMasonry>
```

**Comment by Fuzzo** [comment] 2018-06-18 13:13
May you please try with the following modifications?

1) Wrap the chart in a SimplePanel setting sizes to 100% both on wrapper panel and chart itself
2) Keep the Masonry container, but change the grid equals for all screen sizes grid="l12 m12 s12"

**Comment by nseb** [comment] 2018-06-19 08:08
Same effect , I even changed to use Material Card, it does the same thing. The graph does not have enough space  to be drawn, but I do not understand why.

**Comment by stockiNail** [comment] 2018-06-20 09:34
@nseb we have the feeling that it's a strange behavior of  Masonry container. Nevertheless we need time to setup a test case to address your issue. Hopefully it's ok for you

**Comment by nseb** [comment] 2018-06-21 07:13
@stockiNail no problems

**Comment by stockiNail** [comment] 2020-09-23 22:20
@nseb after a long time I would like to close this issue as we were unable to reproduce it and many other versions have been released.
However, if the problem persists even with the latest versions, feel free to reopen the issue or create a new one and we can try to fix it, if there is a bug.

Thank you very much!

**Closed by stockiNail** 2020-09-23 22:20 UTC
